name: Deploy to production
on:
  push:
    branches:
      -master

jobs:
  test:
    runs.on: ubuntu-lastest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-rubyy@v1
        with:
          bundler-cache: true