# Generated by Django 4.0.2 on 2022-02-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrackerapp', '0002_category_user_program_training_exercise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_program',
            name='program',
            field=models.ManyToManyField(to='fittrackerapp.Program'),
        ),
        migrations.CreateModel(
            name='Exercise_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ManyToManyField(to='fittrackerapp.Exercise')),
                ('program', models.ManyToManyField(to='fittrackerapp.Program')),
            ],
        ),
    ]
