# Generated by Django 4.0.3 on 2022-03-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrackerapp', '0003_user_program_program_exercise_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rank_in_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='number_of_set',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rank_in_program',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
