# Generated by Django 4.0.3 on 2022-04-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fittrackerapp', '0004_training_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='rank_in_program',
            field=models.IntegerField(default=0),
        ),
    ]
