# Generated by Django 3.2.11 on 2022-03-09 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fittrackerapp', '0004_data_rank_in_set_data_value_exercise_number_of_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='value',
        ),
    ]
