# Generated by Django 4.0.2 on 2022-04-10 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fittrackerapp', '0005_alter_exercise_rank_in_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fittrackerapp.category'),
        ),
        migrations.AlterField(
            model_name='program',
            name='discipline',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fittrackerapp.discipline'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise_program',
            unique_together={('exercise', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('date', 'program', 'user')},
        ),
    ]
